# Generated by Django 4.0.2 on 2022-03-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='CLick link to read', max_length=255),
        ),
    ]
